apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy
spec:
  replicas: 2  # Ajusta el número de replicas según tus necesidades
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocdnotification
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argocdnotification
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argocdnotification
    spec:
      containers:
      - name: hw-container
        image: jaimehenao8126/kantox:38933ffd08485630f7f43a9064591e5bde7e0440
        ports:
        - containerPort: 80
