apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy
spec:
  replicas: 2  # Ajusta el número de replicas según tus necesidades
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw-container
<<<<<<< HEAD
        image: jaimehenao8126/kantox:0b7ddd84bc7b8c46aa804717a0e9057df73bed88
=======
        image: jaimehenao8126/kantox:0b7ddd84bc7b8c46aa804717a0e9057df73bed88
>>>>>>> 54bb29f (prueba kube)
        ports:
        - containerPort: 80
