apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy
spec:
  replicas: 2  # Ajusta el número de replicas según tus necesidades
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw-container
        image: jaimehenao8126/kubeops:8e809c71cd65ccec14d90f6b6310171af11f1d78
        ports:
        - containerPort: 80
