apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy
spec:
  replicas: 3  # Ajusta el número de replicas según tus necesidades
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw-container
        image: jaimehenao8126/kantox:8389c0ba1d7759f5ad6a39fef722fc43360266e5
        ports:
        - containerPort: 80
