apiVersion: v1
kind: Service
metadata:
  name: hw-service
spec:
  selector:
    app: hw
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30131  # Especifica aquí el puerto que deseas usar
  type: NodePort
  
