# name: CI

# on:
#   push:
#     branches:
#       - main

# env:
#   IMAGE_NAME: kantox-challenge

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME_JAIME }}
#         password: ${{ secrets.DOCKER_PASSWORD_JAIME }}

#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#         context: ./Docker
#         file: ./Docker/Dockerfile
#         push: true
#         tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

#     - name: Repository Dispatch
#       run: |
#         curl -X POST \
#           -H "Authorization: Bearer ${{ secrets.PAT }}" \
#           -H "Accept: application/vnd.github.everest-preview+json" \
#           -H "Content-Type: application/json" \
#           "https://api.github.com/repos/JaimeHenaoChallange/KubeOps/dispatches" \
#           --data '{"event_type": "new-image", "client_payload": {"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"}}'
