name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kantox-challenge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME_JAIME }}
        password: ${{ secrets.DOCKER_PASSWORD_JAIME }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./Docker
        file: ./Docker/Dockerfile
        push: true
        tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: JaimeHenaoChallange/KubeOps
        event-type: new-image
        client-payload: '{"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"}'



