# name: Update Deployment Image

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

# jobs:
#   update-deployment:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Display Environment Variables
#       run: env

#     - name: List Files in Root
#       run: ls

#     - name: Display Contents of deployment.yaml
#       run: cat deployment.yaml

#     - name: Configure Git User
#       run: |
#         git config --global user.name "GitHub Actions"
#         git config --global user.email "actions@github.com"

#     - name: Debug Git Status
#       run: |
#         git status
#         git log

#     - name: Get the latest image version
#       id: get_latest_image
#       run: echo "::set-output name=latest_image::$(grep -E '^ *image:' deployment.yaml | awk '{print $2}' | sort -V | tail -n 1)"

#     - name: Update Image in deployment.yaml
#       run: |
#         NEW_TAG=${{ github.run_number }}
#         sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:${NEW_TAG}|g" deployment.yaml
#         # Check if there are changes to commit
#         git diff --exit-code deployment.yaml || (git add deployment.yaml && git commit -m "Update image in deployment.yaml" && git push)

#     - name: Debug Git Diff
#       run: git diff deployment.yaml

# name: Update Deployment Image

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

# jobs:
#   update-deployment:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Display Environment Variables
#       run: env

#     - name: List Files in Root
#       run: ls

#     - name: Display Contents of Kubernetes/deployment.yaml
#       run: cat Kubernetes/deployment.yaml

#     - name: Display Contents of Kubernetes/service.yaml
#       run: cat Kubernetes/service.yaml

#     - name: Configure Git User
#       run: |
#         git config --global user.name "GitHub Actions"
#         git config --global user.email "actions@github.com"

#     - name: Debug Git Status
#       run: |
#         git status
#         git log

#     - name: Get the latest image version
#       id: get_latest_image
#       run: echo "::set-output name=latest_image::$(grep -E '^ *image:' Kubernetes/deployment.yaml | awk '{print $2}' | sort -V | tail -n 1)"

#     - name: Update Image in Kubernetes/deployment.yaml
#       run: |
#         NEW_TAG=${{ github.run_number }}
#         sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:${NEW_TAG}|g" Kubernetes/deployment.yaml
#         # Validar cambios antes de commit
#         if git diff --exit-code Kubernetes/deployment.yaml; then
#           echo "No changes to commit."
#         else
#           git add Kubernetes/deployment.yaml
#           git commit -m "Update image in Kubernetes/deployment.yaml - Run ${{ github.run_number }}"
#           git push
#         fi

#     - name: Update Image in Kubernetes/service.yaml
#       run: |
#         NEW_TAG=${{ github.run_number }}
#         sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:${NEW_TAG}|g" Kubernetes/service.yaml
#         # Validar cambios antes de commit
#         if git diff --exit-code Kubernetes/service.yaml; then
#           echo "No changes to commit."
#         else
#           git add Kubernetes/service.yaml
#           git commit -m "Update image in Kubernetes/service.yaml - Run ${{ github.run_number }}"
#           git push
#         fi

#     - name: Debug Git Diff
#       run: git diff Kubernetes/deployment.yaml Kubernetes/service.yaml

name: Update Deployment Image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_FILE: "Kubernetes/deployment.yaml"
      SERVICE_FILE: "Kubernetes/service.yaml"
      GIT_USER_NAME: "GitHub Actions"
      GIT_USER_EMAIL: "actions@github.com"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git User
      run: |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"

    - name: Get the latest image version
      id: get_latest_image
      run: |
        DOCKERHUB_IMAGE=jaimehenao8126/kantox
        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$DOCKERHUB_IMAGE/tags/?page_size=1" | jq -r '.results[0].name')
        echo "::set-output name=latest_image::$DOCKERHUB_IMAGE:$LATEST_TAG"

    - name: Update Image in $DEPLOYMENT_FILE
      run: |
        NEW_TAG=${{ github.run_number }}
        sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:${NEW_TAG}|g" $DEPLOYMENT_FILE
        git diff --exit-code $DEPLOYMENT_FILE || (git add $DEPLOYMENT_FILE && git commit -m "Update image in $DEPLOYMENT_FILE - Run ${{ github.run_number }}" && git push)

    - name: Update Image in $SERVICE_FILE
      run: |
        NEW_TAG=${{ github.run_number }}
        sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:${NEW_TAG}|g" $SERVICE_FILE
        git diff --exit-code $SERVICE_FILE || (git add $SERVICE_FILE && git commit -m "Update image in $SERVICE_FILE - Run ${{ github.run_number }}" && git push)
