# name: Update Deployment Image

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

# jobs:
#   update-deployment:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Display Environment Variables
#       run: env

#     - name: List Files in Root
#       run: ls

#     - name: Display Contents of Kubernetes/deployment.yaml
#       run: cat Kubernetes/deployment.yaml

#     - name: Configure Git User
#       run: |
#         git config --global user.name "GitHub Actions"
#         git config --global user.email "actions@github.com"

#     - name: Debug Git Status
#       run: |
#         git status
#         git log

#     - name: Get the latest image version
#       id: get_latest_image
#       run: |
#         DOCKERHUB_IMAGE=jaimehenao8126/kantox-challenge
#         LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$DOCKERHUB_IMAGE/tags/?page_size=1" | jq -r '.results[0].name')
#         echo "::set-output name=latest_image::$DOCKERHUB_IMAGE:$LATEST_TAG"

#     - name: Update Image in Kubernetes/deployment.yaml
#       run: |
#         NEW_TAG=${{ github.run_number }}
#         sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox-challenge:${NEW_TAG}|g" Kubernetes/deployment.yaml
#         # Check if there are changes to commit
#         git diff --exit-code Kubernetes/deployment.yaml || (git add Kubernetes/deployment.yaml && git commit -m "Update image in Kubernetes/deployment.yaml - Run ${{ github.run_number }}" && git push)

#     - name: Debug Git Diff
#       run: git diff Kubernetes/deployment.yaml
