name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME_JAIME }} -p ${{ secrets.DOCKER_PASSWORD_JAIME }}

    - name: Get the current image count
      id: count
      run: echo "::set-output name=count::$(docker images -q jaimehenao8126/challange-kantox | wc -l)"

    - name: Build and Tag Docker Image
      run: |
        docker build -t jaimehenao8126/challange-kantox:latest -f Docker/Dockerfile .
        docker tag jaimehenao8126/challange-kantox:latest jaimehenao8126/challange-kantox:${{ steps.count.outputs.count }}
      env:
        DOCKER_CLI_ACI: 1

    - name: Push Docker Image
      run: docker push jaimehenao8126/challange-kantox:latest
